<?php

// DO NOT EDIT THIS FILE

// this will autoload the class that we need in our code
spl_autoload_register(function($class) {
 
    // we are assuming that it is in the same directory as this file
    // otherwise we have to do
    // $path = 'path/to/' . $class . ".php"    
    $path =  $class . ".php";
    require $path; 
  
});
 

class CourseDAO {
    public $courses;
    function __construct() {
        $this->courses = [  new Course("Apple LEE","IDIS001","Analytical Skills","TUE","1330",1),
                            new Course("Apple LEE","IS112","Data Management","TUE","830",2),
                           
                         ];
    }

    # This method  retrieves all student names
    function retrieveNames() {
        $result = [];
        foreach($this->courses as $course){
            if(!in_array($course->studentName,$result)){
                // Function in_array checks if the first argument is in the second argument (which is an array)
                $result[] = $course->studentName;
            }
        }
        return $result;
    }
    
    # This method retrieves all courses for a particular student
    function retrieveCourses($student_name) {
        $result = [];
        foreach($this->courses as $course){
            if($course->studentName == $student_name){
                $result[] = $course;
            }
        }
        return $result;
    }

    # This method retrieves courses of $selected_students grouped according to their time slot
    function retrieveCoursesPerTimeSlot($selected_students){
        $result = array();
        $days = ['MON', 'TUE','WED', 'THU', 'FRI'];
        $timings = ['830', '1000', '1200','1330', '1530', '1700'];
        foreach($days as $day){
            foreach($timings as $start_time){
                $result[$day][$start_time] = array();
            }
        }
        foreach($this->courses as $course){
			if(in_array($course->studentName, $selected_students)){
				$result[$course->weekOfDay][$course->startTime][] = $course;
			}
        }
        return $result;
    }
}

?>